import Head from "next/head";
import Post from "~/components/post";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Post />
        <Post />
      </main>
    </>
  );
}
